# Site settings
title: Prajna
description: A book rendered from Wisdom!
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Book settings
book:
  output_dir: docs
  posts_dir: _posts
  template_dir: _layouts
